# Generated by Django 4.0.1 on 2022-01-23 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewer',
            name='image',
            field=models.ImageField(null=True, upload_to='reviewer_image'),
        ),
    ]
