# Generated by Django 4.0.1 on 2022-01-23 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0003_alter_reviewer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewer',
            name='image',
            field=models.ImageField(blank=None, null=True, upload_to='images'),
        ),
    ]
